# ################################################################################
#  Copyright (c) 2026  Claudio André <portfolio-2026br at claudioandre.slmail.me>
#                   ____              __
#                  / __ )____  ____  / /__________ _____ ___  ____
#                 / __  / __ \/ __ \/ __/ ___/ __ `/ __ `__ \/ __ \
#                / /_/ / /_/ / /_/ / /_/ /__/ /_/ / / / / / / /_/ /
#               /_____/\____/\____/\__/\___/\__,_/_/ /_/ /_/ .___/
#                                                         /_/
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# https://www.gnu.org/licenses/gpl-2.0.html
# ################################################################################
# GitHub Action to scan dependency manifest files
# More info at https://github.com/portfolio-2026br/engenharia-software

---
name: Dependency review

"on":
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    name: dependency-review

    if: github.repository == 'portfolio-2026br/engenharia-software'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443
            api.github.com:443
            api.securityscorecards.dev:443
            github.com:443

      - name: "Checkout Repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: "Dependency Review"
        uses: actions/dependency-review-action@595b5aeba73380359d98a5e087f648dbb0edce1b # v4.7.3
